### ISSUE TITLE
I prefer that we dont use the menu bar that's created by default in the electron app

### ISSUE THREAD

**Issue by Lamia-Mihoubi** [Lamia-Mihoubi/MedRDV#4]
I prefer that for the add patient and supprimer patient ykounou included in the page that displau=ys the patients list, just like add RDV and modifier RDV and delete RDV in the mockup I created, what do you think? @SarahNou

**Comment by SarahNou** [comment]
how are we going to access the page that displays the patients list? @Lamia-Mihoubi
